<?php 
/**
 * Implements hook_init().
 *
function home_page_init() {
  if(user_is_anonymous()){
  	variable_set('site_frontpage','node/1');
  }else {
  	variable_set('site_frontpage','node/2');
  }
}
*/


/**
 * Implements hook_menu().
 */
function home_page_menu() {
  $items = array();

  $items['frontpage'] = array(
    'page callback' => 'home_page_frontpage_view',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  return $items;
}


function home_page_frontpage_view(){
	if(user_is_anonymous()){
		drupal_goto('node/1');
	}else {
		drupal_goto('node/2');
	}
}